[project]
name = "auto-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "pandas>=2.3.2",
    "tabulate>=0.9.0",
]
